apiVersion: v1
kind: Service
metadata:
  name: devopsblog-service
spec:
  type: NodePort
  selector:
    app: devopsblog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007

